# render.yaml - Blueprint Specification
# This file is used to define the services for the Render platform.

services:
  # Web Service for the Node.js backend
  - type: web
    name: downloader-backend # The name of your service
    env: node # Specify the environment as Node.js
    plan: free # Use the free instance type
    region: oregon # The region to deploy the service in
    
    # Specify the Node.js and Python versions
    # This ensures both runtimes are available in the build environment.
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: PYTHON_VERSION
        value: 3.11.4
      # Application-specific environment variables
      - key: FILE_LIFETIME_MIN
        value: 15
      - key: MAX_FILE_SIZE
        value: "750m"
      - key: PROCESS_TIMEOUT_SEC
        value: 900
        
    # The build command for your service.
    # It first installs Node.js dependencies, then Python dependencies.
    buildCommand: "npm install"
    
    # A command to run before the start command.
    # We use this to reliably install yt-dlp.
    preDeployCommand: "pip install --upgrade pip && pip install -U yt-dlp"

    # The command to start your service.
    startCommand: "node server.js"
    
    # A health check path that Render uses to determine if the service is live.
    healthCheckPath: /