services:
  - type: web
    name: downloader-backend
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install && pip install --upgrade pip && pip install --no-cache-dir -U yt-dlp"
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.10
      - key: NODE_ENV
        value: production # これでサーバーは本番モードで起動する
      - key: FILE_LIFETIME_MIN
        value: 15
      - key: MAX_FILE_SIZE
        value: 750m
      - key: PROCESS_TIMEOUT_SEC
        value: 900
